name: kmitl
channels:
  - defaults
dependencies:
  - python=3.12.4
  - numpy=1.26.4
  - pandas=2.2.2
  - openpyxl=3.1.4
  - lxml=5.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - statsmodels=0.14.2
  - tensorflow=2.16.1
  - jupyter